services:
  pgvector-db:
    env_file:
      - ./postgres-pgvector/.env
    build:
      dockerfile: postgres.dockerfile
    container_name: postgres-pgvector
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql/init.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
    networks:
      - default

volumes:
  db_data: