package com.pdf.marsk.pdfdemo.service;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true) // Ensure superclass fields are included in equals/hashCode
@ToString(callSuper = true) // Ensure superclass fields are included in toString
public class OcrProgressInfo extends TaskProgressInfo {

    // OcrProgressInfo specific fields
    private String language; // Specific to OCR tasks

    // Constructor for OcrProgressInfo
    public OcrProgressInfo(String taskId, String filename, String initialStage, String language) {
        super(taskId, TaskType.OCR, filename, initialStage); // Call the superclass constructor
        this.language = language;
        // Other fields like progressPercent, message, completed, success are initialized by super constructor
    }

    // Minimal constructor if only taskId and filename are known initially for an OCR task
    public OcrProgressInfo(String taskId, String filename, String language) {
        super(taskId, TaskType.OCR, filename, "OCR Initializing"); // Default initial stage
        this.language = language;
    }

    // Getters and Setters for 'language' will be generated by Lombok's @Data
    // Getters for inherited fields (taskId, filename, currentStage, progressPercent, message, completed, success, createdAt, updatedAt)
    // and Setters (for mutable fields like currentStage, progressPercent, message, completed, success) are available from TaskProgressInfo
    // and will also be correctly handled by Lombok for this subclass.
}
